(defun load-local-file (filename)
  (format t "~%Loading ~A..." filename)
  (load filename))

(load-local-file "./abra-218/general")
(load-local-file "./abra-218/queue")
(load-local-file "./abra-218/ec")
(load-local-file "./abra-218/structures")
(load-local-file "./abra-218/support")
(load-local-file "./abra-218/world")
;(load-local-file "shopping")
(load-local-file "./abra-218/deduction")
(load-local-file "./abra-218/lookahead")
(load-local-file "./abra-218/heuristics")
(load-local-file "./abra-218/inference")
(load-local-file "./abra-218/display")
(load-local-file "./abra-218/init")
