(defun load-local-file (filename)
  (format t "~%Loading ~A..." filename)
  (load filename))

(load-local-file "general")
(load-local-file "queue")
(load-local-file "ec")
(load-local-file "structures")
(load-local-file "support")
(load-local-file "world")
(load-local-file "shopping")
(load-local-file "deduction")
(load-local-file "lookahead")
(load-local-file "heuristics")
(load-local-file "inference")
(load-local-file "display")
(load-local-file "init")
